ls_保险 = ["牛角","女郎","海盗望远镜"]
ls_保险.append("人头像")
print(ls_保险)
ls_保险.insert(0,"步战车")
print(ls_保险)
ls_保险.pop(3)
print(ls_保险)
ls_保险.remove("女郎")
print(ls_保险)
ls_保险.clear()
print(ls_保险)
ls_保险.extend("白绿蓝紫金红")
print(ls_保险)
ls_保险.sort()
print(ls_保险)
ls_保险.reverse()
print(ls_保险)
